# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'macros_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MacroDialog(object):
    def setupUi(self, MacroDialog):
        MacroDialog.setObjectName("MacroDialog")
        MacroDialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(MacroDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.macroGroupBox = QtWidgets.QGroupBox(MacroDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.macroGroupBox.sizePolicy().hasHeightForWidth())
        self.macroGroupBox.setSizePolicy(sizePolicy)
        self.macroGroupBox.setObjectName("macroGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.macroGroupBox)
        self.verticalLayout_2.setContentsMargins(6, 0, 6, 6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listView = QtWidgets.QListView(self.macroGroupBox)
        self.listView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listView.setFrameShadow(QtWidgets.QFrame.Plain)
        self.listView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listView.setTabKeyNavigation(True)
        self.listView.setProperty("showDropIndicator", False)
        self.listView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.listView.setObjectName("listView")
        self.verticalLayout_2.addWidget(self.listView)
        self.verticalLayout.addWidget(self.macroGroupBox)
        self.previewGroupBox = QtWidgets.QGroupBox(MacroDialog)
        self.previewGroupBox.setObjectName("previewGroupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.previewGroupBox)
        self.verticalLayout_3.setContentsMargins(6, 0, 6, 6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.previewLabel = QtWidgets.QLabel(self.previewGroupBox)
        self.previewLabel.setObjectName("previewLabel")
        self.verticalLayout_3.addWidget(self.previewLabel)
        self.verticalLayout.addWidget(self.previewGroupBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(MacroDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(MacroDialog)
        self.buttonBox.accepted.connect(MacroDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(MacroDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MacroDialog)

    def retranslateUi(self, MacroDialog):
        _translate = QtCore.QCoreApplication.translate
        MacroDialog.setWindowTitle(_translate("MacroDialog", "Macros"))
        self.macroGroupBox.setTitle(_translate("MacroDialog", "Macros"))
        self.previewGroupBox.setTitle(_translate("MacroDialog", "Preview"))
        self.previewLabel.setText(_translate("MacroDialog", "test"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MacroDialog = QtWidgets.QDialog()
    ui = Ui_MacroDialog()
    ui.setupUi(MacroDialog)
    MacroDialog.show()
    sys.exit(app.exec_())
